[project]
name = "qwen3-tts-test"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.12.*"
dependencies = [
    "gradio>=5.0,<6.0",
    "numpy>=1.26,<3.0",
    "soundfile>=0.12,<1.0",
    "torch>=2.3.0,<2.10",
    "qwen-tts",
    "numba>=0.59.0",
]
